//! Campus Auth Guardian — Android edition.
//!
//! Re-uses the platform-agnostic core logic (auth, netcheck, guardian, config, logger)
//! and adds an Android-specific ipdetect implementation + UniFFI bindings.

mod auth;
mod config;
mod guardian;
mod ipdetect;
mod logger;
mod netcheck;
mod uniffi_api;

// Re-export for UniFFI (the UDL file references these via crate path)
pub use uniffi_api::*;

// UniFFI scaffolding — generated by build.rs from guardian.udl
// This MUST be included so that UniFFI generates the FFI entry points
// (ffi_guardian_core_android_rustbuffer_alloc, etc.)
include!(concat!(env!("OUT_DIR"), "/guardian.uniffi.rs"));
